name: i_wow
description: Test project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  badges: 2.0.2
  cached_network_image: 3.2.1
  flutter_animate: 1.0.0
  change_app_package_name: ^1.1.0
  flutter_cache_manager: 3.3.0
  flutter_spinkit: 5.1.0
  flutter_svg: 0.22.0
  font_awesome_flutter: 10.1.0
  google_fonts: 3.0.1
  intl: 0.17.0
  json_path: 0.4.1
  page_transition: 2.0.4
  provider: 6.0.4
  timeago: 3.2.2
  url_launcher: 6.1.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  
  bloc: ^8.1.0
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  api_cache_manager: ^1.0.2
  logger: ^1.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  shimmer: ^2.0.0
  flutter_shimmer: ^2.1.2
  photo_view: ^0.14.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/app_launcher_icon.png"
  image_path_android: "assets/images/app_launcher_icon.png"
  adaptive_icon_background: "assets/images/app_launcher_icon.png"
  adaptive_icon_foreground: "assets/images/app_launcher_icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
